### ISSUE TITLE
Where do you get all the pm2 font?

### ISSUE THREAD

**Issue by bettafish15** [eshengsky/pm2-server-monitor#2]
Thanks for your wonderful dashboard. May i ask you where you get your pm2 font for the dashboard? i cant seem to find it anywhere? the font url in font css file seems to belong to you?

**Comment by eshengsky** [comment]
I cannot understand what is 'pm2 font'?
If you means the servers which run with pm2, it is configed here: https://github.com/eshengsky/pm2-server-monitor/blob/master/webUI/config.js

**Comment by bettafish15** [comment]
i mean the the icon for pm2 UI in your dashboard. you declared it through font-face which is in your css file . I want to ask where you get those icons bro.

**Comment by eshengsky** [comment]
I use [iconfont](https://www.iconfont.cn/) - alibaba's icon library.
https://github.com/eshengsky/pm2-server-monitor/blob/master/webUI/static/iconfont.css

**Comment by bettafish15** [comment]
Thanks man ! I appreciate it !!
